import type { Locale } from "@kidz/contracts";

const copy = {
  ru: {
    brandLine: "Гардероб растёт вместе с тобой",
    next: "Продолжить",
    back: "Назад",
    languageEyebrow: "Сначала — твой язык",
    languageTitle: "Choose how Kidz speaks",
    languageBody: "Названия стилей, рекомендации и уведомления будут на выбранном языке.",
    profileEyebrow: "Возраст и свобода выбора",
    profileTitle: "Кто сегодня решает?",
    profileBody: "Возраст задаёт стартовый режим. Его всегда можно изменить под вашу семью.",
    age: "Возраст",
    parentDecides: "Решает взрослый",
    parentDecidesBody: "Практичные подсказки и полный контроль гардероба.",
    together: "Выбираем вместе",
    togetherBody: "Несколько безопасных вариантов и право выбора.",
    userDecides: "Решаю сам·а",
    userDecidesBody: "Погода — контекст, стиль и финальное решение — твои.",
    appearanceTitle: "Полный образ",
    appearanceBody: "Пол/подача, длина и цвет волос помогут подбирать причёску, украшения, сумку и мягкие hair-ссылки под стиль.",
    genderPresentation: "Пол / подача стиля",
    hairLength: "Длина волос",
    hairColor: "Цвет волос",
    styleEyebrow: "Личный стиль",
    styleTitle: "Смешай свой характер",
    styleBody: "Выбери до трёх направлений. Это не ярлык — пропорции можно менять каждый день.",
    selected: "Выбрано",
    searchStyle: "Найти стиль: emo, Stockholm, acubi…",
    wardrobeEyebrow: "Реальные вещи",
    wardrobeTitle: "Начни с малого",
    wardrobeBody: "Можно начать с пары вещей или загрузить реалистичный демо-шкаф: одежда, обувь, сумки, украшения и головные уборы.",
    addPhoto: "Добавить фото",
    addDemo: "Реальный демо-шкаф",
    quickAdd: "Быстро добавить",
    wardrobeEmpty: "Здесь появятся вещи, которые действительно есть в шкафу.",
    cutoutPending: "вырезка ждёт обработки",
    buildLooks: "Собрать три образа",
    outfitsEyebrow: "Сегодня · +8 °C · ветер вечером",
    outfitsTitle: "Три версии тебя",
    outfitsBody: "Не команды, а варианты. Можно оставить основу и заменить одну вещь.",
    look: "Образ",
    choose: "Выбрать этот",
    newSet: "Собрать заново",
    localMode: "Локальный режим",
    onlineMode: "Сохранено в staging",
    localModeBody: "API пока недоступен — образы собраны тем же engine прямо на устройстве.",
    loading: "Собираем сочетания…",
    styleMatch: "совпадает с выбранным стилем",
    hairDirection: "есть направление для причёски",
    makeupDirection: "есть makeup-направление",
    accessoryBalance: "аксессуары поддерживают образ",
    accessoryIdea: "есть идея для аксессуаров",
    coolLayer: "есть слой для прохладного утра",
    completeLook: "все основные части на месте",
    partial: "гардероб пока неполный",
  },
  en: {
    brandLine: "A wardrobe that grows with you",
    next: "Continue",
    back: "Back",
    languageEyebrow: "First — your language",
    languageTitle: "Choose how Kidz speaks",
    languageBody: "Style names, recommendations and notifications follow your language.",
    profileEyebrow: "Age and autonomy",
    profileTitle: "Who decides today?",
    profileBody: "Age suggests a starting mode. Your family can always change it.",
    age: "Age",
    parentDecides: "Adult decides",
    parentDecidesBody: "Practical guidance and full wardrobe control.",
    together: "Choose together",
    togetherBody: "Several sound options with room to choose.",
    userDecides: "I decide",
    userDecidesBody: "Weather is context. Style and the final call are yours.",
    appearanceTitle: "Total look",
    appearanceBody: "Gender/presentation, hair length and hair color help suggest hair, jewelry, bags and soft color references for the style.",
    genderPresentation: "Gender / style presentation",
    hairLength: "Hair length",
    hairColor: "Hair color",
    styleEyebrow: "Personal style",
    styleTitle: "Mix your own character",
    styleBody: "Pick up to three directions. It is not a label — change the mix any day.",
    selected: "Selected",
    searchStyle: "Find a style: emo, Stockholm, acubi…",
    wardrobeEyebrow: "Real clothes",
    wardrobeTitle: "Start small",
    wardrobeBody: "Start with a few pieces or load a realistic demo closet: clothes, shoes, bags, jewelry and headwear.",
    addPhoto: "Add a photo",
    addDemo: "Real demo closet",
    quickAdd: "Quick add",
    wardrobeEmpty: "The clothes you actually own will appear here.",
    cutoutPending: "cutout pending",
    buildLooks: "Build three looks",
    outfitsEyebrow: "Today · 8 °C · wind later",
    outfitsTitle: "Three versions of you",
    outfitsBody: "Options, not orders. Keep the base and swap one piece.",
    look: "Look",
    choose: "Choose this",
    newSet: "Build again",
    localMode: "Local mode",
    onlineMode: "Saved to staging",
    localModeBody: "The API is not available, so the same engine built these looks on-device.",
    loading: "Building combinations…",
    styleMatch: "matches your selected style",
    hairDirection: "includes hair direction",
    makeupDirection: "includes makeup direction",
    accessoryBalance: "accessories support the look",
    accessoryIdea: "includes an accessory idea",
    coolLayer: "includes a layer for the cool morning",
    completeLook: "all core pieces are present",
    partial: "the wardrobe is still incomplete",
  },
} as const;

export type CopyKey = keyof (typeof copy)["ru"];
export const t = (locale: Locale, key: CopyKey) => copy[locale][key];
